# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/elisedonszelmann-lund/BrainShiftVisualizer/BrainShiftVisualizer/BrainShiftModule/Resources/UI/BrainShiftModule.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BrainShiftModule(object):
    def setupUi(self, BrainShiftModule):
        BrainShiftModule.setObjectName("BrainShiftModule")
        BrainShiftModule.resize(568, 497)
        self.verticalLayout = QtWidgets.QVBoxLayout(BrainShiftModule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputsCollapsibleButton = ctkCollapsibleButton(BrainShiftModule)
        self.outputsCollapsibleButton.setEnabled(True)
        self.outputsCollapsibleButton.setObjectName("outputsCollapsibleButton")
        self.formLayout_4 = QtWidgets.QFormLayout(self.outputsCollapsibleButton)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.referenceVolume = qMRMLNodeComboBox(self.outputsCollapsibleButton)
        self.referenceVolume.setNodeTypes(['vtkMRMLScalarVolumeNode'])
        self.referenceVolume.setShowChildNodeTypes(False)
        self.referenceVolume.setNoneEnabled(True)
        self.referenceVolume.setAddEnabled(True)
        self.referenceVolume.setRemoveEnabled(True)
        self.referenceVolume.setObjectName("referenceVolume")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.referenceVolume)
        self.label_6 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.transformNode = qMRMLNodeComboBox(self.outputsCollapsibleButton)
        self.transformNode.setNodeTypes([])
        self.transformNode.setHideChildNodeTypes([])
        self.transformNode.setInteractionNodeSingletonTag("")
        self.transformNode.setObjectName("transformNode")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.transformNode)
        self.label_3 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.displacementMagnitudeVolume = qMRMLCheckableNodeComboBox(self.outputsCollapsibleButton)
        self.displacementMagnitudeVolume.setAddEnabled(True)
        self.displacementMagnitudeVolume.setRenameEnabled(True)
        self.displacementMagnitudeVolume.setObjectName("displacementMagnitudeVolume")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.displacementMagnitudeVolume)
        self.label_4 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.existingDisplacementVolumeSelector = qMRMLCheckableNodeComboBox(self.outputsCollapsibleButton)
        self.existingDisplacementVolumeSelector.setObjectName("existingDisplacementVolumeSelector")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.existingDisplacementVolumeSelector)
        self.loadDisplacementVolumeButton = QtWidgets.QPushButton(self.outputsCollapsibleButton)
        self.loadDisplacementVolumeButton.setObjectName("loadDisplacementVolumeButton")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.loadDisplacementVolumeButton)
        self.label_5 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.colorMapSelector = qMRMLColorTableComboBox(self.outputsCollapsibleButton)
        self.colorMapSelector.setObjectName("colorMapSelector")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.colorMapSelector)
        self.backgroundVolume = qMRMLNodeComboBox(self.outputsCollapsibleButton)
        self.backgroundVolume.setNodeTypes([])
        self.backgroundVolume.setHideChildNodeTypes([])
        self.backgroundVolume.setInteractionNodeSingletonTag("")
        self.backgroundVolume.setObjectName("backgroundVolume")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.backgroundVolume)
        self.applyButton = QtWidgets.QPushButton(self.outputsCollapsibleButton)
        self.applyButton.setEnabled(False)
        self.applyButton.setObjectName("applyButton")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.applyButton)
        self.verticalLayout.addWidget(self.outputsCollapsibleButton)

        self.retranslateUi(BrainShiftModule)
        BrainShiftModule.mrmlSceneChanged['vtkMRMLScene*'].connect(self.referenceVolume.setMRMLScene) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BrainShiftModule)

    def retranslateUi(self, BrainShiftModule):
        _translate = QtCore.QCoreApplication.translate
        self.outputsCollapsibleButton.setText(_translate("BrainShiftModule", "Inputs"))
        self.label_2.setText(_translate("BrainShiftModule", "Mapping Image:"))
        self.referenceVolume.setToolTip(_translate("BrainShiftModule", "Pick the output to the algorithm."))
        self.referenceVolume.setProperty("SlicerParameterName", _translate("BrainShiftModule", "referenceVolume"))
        self.label_6.setText(_translate("BrainShiftModule", "Background Image:"))
        self.label.setText(_translate("BrainShiftModule", "Transformation:"))
        self.transformNode.setProperty("SlicerParameterName", _translate("BrainShiftModule", "transformNode"))
        self.label_3.setText(_translate("BrainShiftModule", "Output Volume:"))
        self.label_4.setText(_translate("BrainShiftModule", "Load Volume:"))
        self.loadDisplacementVolumeButton.setText(_translate("BrainShiftModule", "Load Volume"))
        self.label_5.setText(_translate("BrainShiftModule", "Color Map:"))
        self.applyButton.setToolTip(_translate("BrainShiftModule", "Run the algorithm."))
        self.applyButton.setText(_translate("BrainShiftModule", "Compute Mapping"))
from ctkCollapsibleButton import ctkCollapsibleButton
from qMRMLCheckableNodeComboBox import qMRMLCheckableNodeComboBox
from qMRMLColorTableComboBox import qMRMLColorTableComboBox
from qMRMLNodeComboBox import qMRMLNodeComboBox
from qMRMLWidget import qMRMLWidget
