# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/elisedonszelmann-lund/BrainShiftVisualizer/BrainShiftVisualizer/BrainShiftModule/Resources/UI/BrainShiftModule.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BrainShiftModule(object):
    def setupUi(self, BrainShiftModule):
        BrainShiftModule.setObjectName("BrainShiftModule")
        BrainShiftModule.resize(399, 422)
        self.verticalLayout = QtWidgets.QVBoxLayout(BrainShiftModule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputsCollapsibleButton = ctkCollapsibleButton(BrainShiftModule)
        self.outputsCollapsibleButton.setObjectName("outputsCollapsibleButton")
        self.formLayout_4 = QtWidgets.QFormLayout(self.outputsCollapsibleButton)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.referenceVolume = qMRMLNodeComboBox(self.outputsCollapsibleButton)
        self.referenceVolume.setNodeTypes(['vtkMRMLScalarVolumeNode'])
        self.referenceVolume.setShowChildNodeTypes(False)
        self.referenceVolume.setNoneEnabled(True)
        self.referenceVolume.setAddEnabled(True)
        self.referenceVolume.setRemoveEnabled(True)
        self.referenceVolume.setObjectName("referenceVolume")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.referenceVolume)
        self.transformNode = qMRMLNodeComboBox(self.outputsCollapsibleButton)
        self.transformNode.setNodeTypes([])
        self.transformNode.setHideChildNodeTypes([])
        self.transformNode.setInteractionNodeSingletonTag("")
        self.transformNode.setObjectName("transformNode")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.transformNode)
        self.applyButton = QtWidgets.QPushButton(self.outputsCollapsibleButton)
        self.applyButton.setEnabled(False)
        self.applyButton.setObjectName("applyButton")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.applyButton)
        self.label_4 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.opacitySlider = qMRMLSliderWidget(self.outputsCollapsibleButton)
        self.opacitySlider.setSingleStep(0.05)
        self.opacitySlider.setPageStep(1.0)
        self.opacitySlider.setMaximum(1.0)
        self.opacitySlider.setProperty("value", 0.5)
        self.opacitySlider.setQuantity("")
        self.opacitySlider.setObjectName("opacitySlider")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.opacitySlider)
        self.label_3 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.displacementMagnitudeVolume = qMRMLCheckableNodeComboBox(self.outputsCollapsibleButton)
        self.displacementMagnitudeVolume.setAddEnabled(True)
        self.displacementMagnitudeVolume.setRenameEnabled(True)
        self.displacementMagnitudeVolume.setObjectName("displacementMagnitudeVolume")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.displacementMagnitudeVolume)
        self.label = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_5 = QtWidgets.QLabel(self.outputsCollapsibleButton)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fixedVolume = qMRMLNodeComboBox(self.outputsCollapsibleButton)
        self.fixedVolume.setNodeTypes([])
        self.fixedVolume.setHideChildNodeTypes([])
        self.fixedVolume.setInteractionNodeSingletonTag("")
        self.fixedVolume.setObjectName("fixedVolume")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fixedVolume)
        self.verticalLayout.addWidget(self.outputsCollapsibleButton)

        self.retranslateUi(BrainShiftModule)
        BrainShiftModule.mrmlSceneChanged['vtkMRMLScene*'].connect(self.referenceVolume.setMRMLScene) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BrainShiftModule)

    def retranslateUi(self, BrainShiftModule):
        _translate = QtCore.QCoreApplication.translate
        self.outputsCollapsibleButton.setText(_translate("BrainShiftModule", "Inputs"))
        self.label_2.setText(_translate("BrainShiftModule", "Reference:"))
        self.referenceVolume.setToolTip(_translate("BrainShiftModule", "Pick the output to the algorithm."))
        self.referenceVolume.setProperty("SlicerParameterName", _translate("BrainShiftModule", "referenceVolume"))
        self.transformNode.setProperty("SlicerParameterName", _translate("BrainShiftModule", "transformNode"))
        self.applyButton.setToolTip(_translate("BrainShiftModule", "Run the algorithm."))
        self.applyButton.setText(_translate("BrainShiftModule", "Apply"))
        self.label_4.setText(_translate("BrainShiftModule", "Opacity Slider"))
        self.label_3.setText(_translate("BrainShiftModule", "Output Volume:"))
        self.label.setText(_translate("BrainShiftModule", "Transformation:"))
        self.label_5.setText(_translate("BrainShiftModule", "iUS:"))
from ctkCollapsibleButton import ctkCollapsibleButton
from qMRMLCheckableNodeComboBox import qMRMLCheckableNodeComboBox
from qMRMLNodeComboBox import qMRMLNodeComboBox
from qMRMLSliderWidget import qMRMLSliderWidget
from qMRMLWidget import qMRMLWidget
